#!/bin/bash

set -e
set -o pipefail

# check the ssh directory for a key
echo "Contents of ~/.ssh directory:"
ls -al ~/.ssh
echo "If there's no <key> and <key>.pub, you'll need a new SSH key."
echo "Create a new SSH key? (y/n)"
read -n 1 -r CREATE
echo
if [[ $CREATE =~ ^[Yy]$ ]]
then
    # configure SSH agent and SSH key, and pass to github
    source ./steps/create-ssh-key
fi

# create src directory
source ./steps/create-src-directory

# install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install dev tools
source ./steps/install-dev-tools

# install a few productivity tools
source ./steps/install-productivity-tools

# install OhMyZsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
